### ISSUE TITLE
MAX44009 - ctor calls Wire.begin

### ISSUE THREAD

**Issue by raghur** [RobTillaart/Arduino#127]
So I ran into this while trying to use this library with the bluepill (STM32f103)... basically, the code would never proceed beyond hte object declaration on L15:

https://github.com/RobTillaart/Arduino/blob/939136867bf74fa569f51d495425898b15e8a8f0/libraries/Max44009/examples/max44009_test01/max44009_test01.ino#L15

After much head scratching, it turned out that moving the `Wire.begin()` call within `setup()` is needed. Which brings to question - was this ever functional/working?

**Comment by RobTillaart** [comment]
Yes, but only tested on an UNO

Been a long time since I worked with that sensor, none lying around to do a quick test uinfortunately.
The last fix and test was - https://github.com/RobTillaart/Arduino/issues/117 - and worked on an ESP8266 according to Bolukan.
I just tried to compile the example of library for an UNO (I have nearby) and the library seems to be broken by the fix for ESP issue #117 as it complains about the Wire.begin() call not supported. Removing the "ESP8622" call to wire.begin(clk, dta) solves it for the UNO. I should have tested the ESP fix for UNO platform, sorry.

==> The lib should use conditional compilation to fix this properly for the UNO and ESP8266

Wire.begin() should be in setup() as you propose as it depends on the compiler when it calls the ctor of the max44009 object and therefor to the begin() call. Would be a (small) breaking change for the interface of the lib.

I'll put both on my todo list but it will take time (need a sensor for decent test).

Thanks for pointing out.
