### ISSUE TITLE
AD524X

### ISSUE THREAD

**Issue by Manhem** [RobTillaart/Arduino#170]
Hi. 
I just wonder if the AD524X library for Arduino also works for AD5144?

**Comment by RobTillaart** [comment]
Hi,
Never worked with the AD5144, I would need to check the datasheet to see if there is a (partial) match. 
or you can just give it a try...

**Comment by RobTillaart** [comment]
Better discuss topic at its main repo - https://github.com/RobTillaart/AD524X

**Comment by RobTillaart** [comment]
A quick look shows the AD5144 has 4 potmeters so best case it will work for only two of them...
And more important the AD5144 is a SPI device so that will not work with this I2C based lib.
Sorry...

The AD5144A is an I2C variant of the chip.

https://www.analog.com/media/en/technical-documentation/data-sheets/AD5124_5144_5144A.pdf

Based upon this lib it might not be too difficult to derive an AD5144A library.

**Comment by Manhem** [comment]
Sorry.
I forgot the A at the end.
It's a AD5144A.
So if you have time and want to help me, can you see if you can implementate the AD5144A in you library?
I will be very greatful if you can help me.

**Comment by RobTillaart** [comment]
Created an empty repo - https://github.com/RobTillaart/AD5144A - to develop a library
I cannot promise any timescale but I have some time this weekend so lets see how far we can go.
As I do not have any hardware I rely on your testing ...

Please reopen this issue there, please add a link to this one (so this issue can be closed.
